apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../pvc.yaml
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../pdb.yaml
  - ../../networkpolicy.yaml
  - ../../agent-deployment.yaml
images:
  - name: ghcr.io/kronosbackup/kronos
    newName: ghcr.io/kronosbackup/kronos
    digest: sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
