apiVersion: v1
kind: Service
metadata:
  name: kronos-control-plane
  namespace: kronos
  labels:
    app.kubernetes.io/name: kronos
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kronos
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: 8500
      targetPort: http
